// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Octopus.Server.Persistence.EfCore;

#nullable disable

namespace Octopus.Server.Persistence.EfCore.Migrations
{
    [DbContext(typeof(OctopusDbContext))]
    [Migration("20260126173029_AddIfcProperties")]
    partial class AddIfcProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Octopus.Server.Domain.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StorageKey");

                    b.HasIndex("ProjectId", "Category");

                    b.HasIndex("ProjectId", "IsDeleted");

                    b.HasIndex("ProjectId", "Kind");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.FileLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("TargetFileId");

                    b.HasIndex("SourceFileId", "LinkType");

                    b.HasIndex("TargetFileId", "LinkType");

                    b.ToTable("FileLinks", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityLabel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeObjectName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeObjectType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("ModelVersionId", "EntityLabel")
                        .IsUnique();

                    b.HasIndex("ModelVersionId", "GlobalId");

                    b.HasIndex("ModelVersionId", "TypeName");

                    b.ToTable("IfcElements", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertySetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertySetId");

                    b.HasIndex("PropertySetId", "Name");

                    b.ToTable("IfcProperties", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcPropertySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTypePropertySet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("ElementId", "Name");

                    b.ToTable("IfcPropertySets", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcQuantity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuantitySetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuantitySetId");

                    b.HasIndex("QuantitySetId", "Name");

                    b.ToTable("IfcQuantities", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcQuantitySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("ElementId", "Name");

                    b.ToTable("IfcQuantitySets", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IfcFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertiesFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WexBimFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IfcFileId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PropertiesFileId");

                    b.HasIndex("Status");

                    b.HasIndex("WexBimFileId");

                    b.HasIndex("ModelId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ModelVersions", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.ProjectMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMemberships", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.UploadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommittedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommittedFileId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("UploadSessions", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.WorkspaceInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WorkspaceInvites", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships", (string)null);
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.FileLink", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "SourceFile")
                        .WithMany("SourceLinks")
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "TargetFile")
                        .WithMany("TargetLinks")
                        .HasForeignKey("TargetFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceFile");

                    b.Navigation("TargetFile");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcElement", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.ModelVersion", "ModelVersion")
                        .WithMany()
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcProperty", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.IfcPropertySet", "PropertySet")
                        .WithMany("Properties")
                        .HasForeignKey("PropertySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertySet");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcPropertySet", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.IfcElement", "Element")
                        .WithMany("PropertySets")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcQuantity", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.IfcQuantitySet", "QuantitySet")
                        .WithMany("Quantities")
                        .HasForeignKey("QuantitySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuantitySet");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcQuantitySet", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.IfcElement", "Element")
                        .WithMany("QuantitySets")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Model", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.Project", "Project")
                        .WithMany("Models")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.ModelVersion", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "IfcFile")
                        .WithMany()
                        .HasForeignKey("IfcFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Octopus.Server.Domain.Entities.Model", "Model")
                        .WithMany("Versions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "PropertiesFile")
                        .WithMany()
                        .HasForeignKey("PropertiesFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "WexBimFile")
                        .WithMany()
                        .HasForeignKey("WexBimFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IfcFile");

                    b.Navigation("Model");

                    b.Navigation("PropertiesFile");

                    b.Navigation("WexBimFile");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Project", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.ProjectMembership", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.Project", "Project")
                        .WithMany("Memberships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octopus.Server.Domain.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.UploadSession", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.FileEntity", "CommittedFile")
                        .WithMany()
                        .HasForeignKey("CommittedFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Octopus.Server.Domain.Entities.Project", "Project")
                        .WithMany("UploadSessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommittedFile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.WorkspaceInvite", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.User", "AcceptedByUser")
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Octopus.Server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Invites")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcceptedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.WorkspaceMembership", b =>
                {
                    b.HasOne("Octopus.Server.Domain.Entities.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Octopus.Server.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("SourceLinks");

                    b.Navigation("TargetLinks");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcElement", b =>
                {
                    b.Navigation("PropertySets");

                    b.Navigation("QuantitySets");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcPropertySet", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.IfcQuantitySet", b =>
                {
                    b.Navigation("Quantities");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Model", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Project", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Memberships");

                    b.Navigation("Models");

                    b.Navigation("UploadSessions");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectMemberships");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("Octopus.Server.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Invites");

                    b.Navigation("Memberships");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
